# NUMPY

In [5]:
##### call library in python
# call numpy

import numpy as np

In [7]:
print(np.__version__)

2.4.4


In [10]:
# if 1. something, upgrade the version 

!pip install --upgrade numpy

# then, go to kernel and restart > run np.__version__

# create array from list 

lists=[1.2,2,3,4,5]

#put in array 'x' for example 
x=np.array(lists)
print(x)

In [51]:
x.shape
# means to check 

(5,)

In [53]:
x.dtype
# to check data type

dtype('float64')

#### shortcut

In [46]:
y=np.array([1,2,3,4,5])

In [48]:
print(y)

[1 2 3 4 5]


#### another example 

In [59]:
# making array of size 6 of zeros
z=np.zeros(6)
print(z)

[0. 0. 0. 0. 0. 0.]


In [61]:
# making array of size 6 of 1
z=np.ones(6)
print(z)

[1. 1. 1. 1. 1. 1.]


##### arrange

In [65]:
a=np.arange(0,11,2)
print(a)

[ 0  2  4  6  8 10]


In [67]:
b=np.linspace(0, 1, 5)
print(b)

[0.   0.25 0.5  0.75 1.  ]


### create 2D array 

In [72]:
#2 rows X 3 column

a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [74]:
a.shape

(2, 3)

## create 3D array

In [83]:
a3=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(a3)
a3.shape

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


(3, 2, 2)

In [85]:
a3.dtype

dtype('int64')

##### another example

In [88]:
# 3D array 2x3 with 2 depth
a4=np.array([[[1,2,3],[3,4,5]],[[6,7,8],[9,10,11]]])
a4.shape

# the output explanation : 
# first depth
# second number of row
# 3rd number of column

(2, 2, 3)

In [90]:
a4.ndim
# to check number of dimension

3

In [92]:
a4.size
# total number of elements

12

### Indexing

##### 1D ARRAY

In [116]:
a1=np.array([1,2,3,4,5])

# to abstract num 3 only:
print(a1[2])

# because 3 is at index 2 so put 2 in the bracket

3


##### 2D array

In [122]:
a2=np.array([[1,2,3],[4,5,6]])
a2[1,1]
# to call index number 4 = 5

np.int64(5)

In [124]:
a2[1,2]

np.int64(6)

##### 3D array

In [129]:
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3[1,0,1])

8


In [137]:
### exercise : create a 3D array depth 2 row 2 col 2. write index to access 5

a4=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a4[1,0,0])

5


## Fancy Indexing

In [146]:
# want output item at position 2 and 4
# 1D : 

a1=np.array([1,2,3,4,5])
print(a1[[2,4]])

[3 5]


In [156]:
# 2D : 

a2=np.array([[1,2,3],[4,5,6]])
print(a2[[0,1]])                      # calling row

[[1 2 3]
 [4 5 6]]


In [158]:
print(a2[:,[0,1]])                      # calling column

[[1 2]
 [4 5]]


### boolean indexing 

In [163]:
# 1D

a1=np.array([1,2,3,4,5])
cond=a1>2
print(cond)
print(a1[cond])

[False False  True  True  True]
[3 4 5]


In [171]:
# multiple cond

a2=np.array([[1,2,3],[4,5,6]])
cond=(a2>2)&(a2<5)

print(cond)
print(a2[cond])

[[False False  True]
 [ True False False]]
[3 4]


### array slicing

In [193]:
a1=np.array([1,2,3,4,5,6,7,8,9,10])

#slice position 2 until 4
a1[1:4]

array([2, 3, 4])

In [199]:
a1=np.array([1,2,3,4,5,6,7,8,9,10])
a1[1:10:2]

array([ 2,  4,  6,  8, 10])

In [201]:
a1=np.array([1,2,3,4,5,6,7,8,9,10])
a1[:5]

array([1, 2, 3, 4, 5])

In [203]:
a1=np.array([1,2,3,4,5,6,7,8,9,10])
a1[5:]

array([ 6,  7,  8,  9, 10])

In [205]:
# 2D :

In [209]:
a2=np.array([[1,2,3],[3,4,5]])
a2[0,1:]                    

# 0 means first row 
# 1: means column 1 til end 

array([2, 3])

In [212]:
a3=np.array([[[1,2,3],[4,5,6]],
             [[7,8,9],[10,11,12]]])

a3[:,1,:2]

array([[ 4,  5],
       [10, 11]])

### Array manipulations

In [216]:
a=np.array([1,2,3,4,5,6])
a=a.reshape(2,3)
print(a)

# 1D -> 2D


[[1 2 3]
 [4 5 6]]


In [220]:
a1=np.array([1,2,3])
a2=np.array([3,4,5])

np.concatenate((a1,a2))

array([1, 2, 3, 3, 4, 5])

In [222]:
a1=np.array([1,2,3])
a2=np.array([3,4,5])

np.concatenate((a1,a2), axis=0)

array([1, 2, 3, 3, 4, 5])

In [228]:
# 2D :

a3=np.array([[1,2],[3,4]])
a4=np.array([[5,6],[7,8]])

np.concatenate((a3,a4), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [230]:
a3=np.array([[1,2],[3,4]])
a4=np.array([[5,6],[7,8]])

np.vstack((a3,a4))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [232]:
a=np.array([1,2,3,4,5,6])
np.split(a,2)                  #no need axis if 1D

[array([1, 2, 3]), array([4, 5, 6])]

In [234]:
# 2D :

a3=np.array([[1,2],[3,4]])
np.split(a3,2,axis=1)                  #need axis if 2D

[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [236]:
# 2D :

a3=np.array([[1,2],[3,4]])
np.vsplit(a3,2)                  #no need axis if vsplit

[array([[1, 2]]), array([[3, 4]])]

In [244]:
arr=np.arange(18)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [248]:
#reshape code atas 

arr=np.arange(18).reshape(3,3,2)
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [254]:
np.split(arr,3,axis=0)

[array([[[0, 1],
         [2, 3],
         [4, 5]]]),
 array([[[ 6,  7],
         [ 8,  9],
         [10, 11]]]),
 array([[[12, 13],
         [14, 15],
         [16, 17]]])]

In [258]:
np.vsplit(arr,3)

[array([[[0, 1],
         [2, 3],
         [4, 5]]]),
 array([[[ 6,  7],
         [ 8,  9],
         [10, 11]]]),
 array([[[12, 13],
         [14, 15],
         [16, 17]]])]

## Ufunc

In [281]:
a=np.arange(0,10)
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [283]:
a=np.arange(0,10)
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [287]:
a=np.arange(0,10)
print(np.max(a))

9


In [295]:
a=np.array([9,4,6,7,2,3])
print(np.argmax(a))

# tells which index has max value

0


##### binary ufunc

In [300]:
a=np.array([1,2,3])
b=np.array([4,5,6])

np.add(a,b)

array([5, 7, 9])

In [302]:
a=np.array([1,2,3])
b=np.array([4,5,6])

a+b

array([5, 7, 9])

In [306]:
# kenapa kena ada np.add while boleh je tulis a+b? sbb this condition : 

a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.zeros(3)

np.add(a,b,out=c)

array([5., 7., 9.])

## view and copy

In [313]:
# original array 
arr=np.arange(5)
print(arr)

# the view array
view_arr=arr[1:4]       #basic slicing 
print(view_arr)
view_arr[0]=999        # replace index 0 with number 999

[0 1 2 3 4]
[1 2 3]


In [319]:
print("Array after tempering :")
print("View array :")
print(arr)
print("Original Array")
print(view_arr)    

# check output
# the original also change 
# how?

Array after tempering :
View array :
[  0 999   2   3   4]
Original Array
[999   2   3]


In [321]:
# to avoid tempering original data :

# original array 
arr=np.arange(5)
print(arr)

# the view array (after tempering)
view_arr=arr[1:4].copy()       #basic slicing 
print(view_arr)
view_arr[0]=999        # replace index 0 with number 999

print("Array after tempering :")
print("View array :")
print(arr)
print("Original Array")
print(view_arr)  

[0 1 2 3 4]
[1 2 3]
Array after tempering :
View array :
[0 1 2 3 4]
Original Array
[999   2   3]


##### other example with fancy indexing :

In [326]:
# if use fancy slicing, no need to use .copy()

arr=np.arange(5)
print(arr)

# the view array (after tempering)
view_arr=arr[[2,3,4]]          #fancy indexing
print(view_arr)

view_arr[0]=999                #replace index 0 with number 999

print("\nArray after tempering :")
print("View array :")
print(arr)
print("Original Array")
print(view_arr)

[0 1 2 3 4]
[2 3 4]

Array after tempering :
View array :
[0 1 2 3 4]
Original Array
[999   3   4]


##### exercise :

In [329]:
#lets do data filtering 

grades=np.array([85,92,78,95,88,76,91,83])
print("Grades: ", grades)

Grades:  [85 92 78 95 88 76 91 83]


In [331]:
# 1) find student who got A (>=80) hint: np.where 

# 2) num of students who got excellent grade (>=90)

# 3) find student with the top mark 

In [343]:
# Q1
# use cond boolean 

(grades>=80)

array([ True,  True, False,  True,  True, False,  True,  True])

In [345]:
np.where(grades>=80)

(array([0, 1, 3, 4, 6, 7]),)

In [347]:
# Q2 -------------------------------------------------------------------------

(grades>=90)

array([False,  True, False,  True, False, False,  True, False])

In [351]:
# kira boolean 1 true ada berapa banyak
np.sum(grades>=90)

np.int64(3)

In [354]:
arr_excel=grades[(grades>=90)]
arr_excel.size

# same output with atas 

3

In [366]:
# Q3 --------------------------------------------------------------------------
# 3) find student with the top mark

grades=np.array([85,92,78,95,88,76,91,83])
print("Grades: ", grades)

Grades:  [85 92 78 95 88 76 91 83]


In [368]:
np.argmax(grades)

# meaning index ke 3 

np.int64(3)